### ISSUE TITLE
Link to redbarn is 404

### ISSUE THREAD

**Issue by jpmens** [m3047/rear_view_rpz#2]
The link to http://lists.redbarn.org/pipermail/dnsfirewalls/2021-November/000422.html is 404, and http://lists.redbarn.org/pipermail is also 404 … 

Wrong server maybe?

**Comment by m3047** [comment]
That's Paul Vixie's vanity domain, maybe he's taking a vacation? I changed the link to the repost to `bind-users@`: https://lists.isc.org/pipermail/bind-users/2021-December/105450.html
